TRUNCATE TABLE coupon CASCADE;
TRUNCATE TABLE pending_add CASCADE;

ALTER TABLE coupon
    ADD COLUMN IF NOT EXISTS min_check NUMERIC(10, 2) NOT NULL;

ALTER TABLE pending_add
    ADD COLUMN IF NOT EXISTS min_check NUMERIC(10, 2) NOT NULL;
